[tool.poetry]
name = "xeda"
version = "0.0.2"
description = "X-vendor, X-technology, X-platform Electronic Design Abstraction and Automation"
authors = ["Kamyar Mohajerani <kammoh@gmail.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8,^3.7,^3.6"
Jinja2 = "^2.11.2"
colored = "^1.4.2"
progress = "^1.5"
coloredlogs = "^14.0"
Pebble = "^4.5.3"
numpy = "^1.19.2"
tomlkit = "^0.7.0"

[tool.poetry.dev-dependencies]

[tool.poetry-dynamic-versioning]
# enable = true
# vcs = "git"
# style = "semver"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry>=1.0.2", "poetry-dynamic-versioning"]
build-backend = "poetry.masonry.api"
