name: CI
on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: ["master", "dev"]
  workflow_dispatch:

jobs:
  mypy:
    name: CI Tests
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: "actions/checkout@v2"
      - uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel virtualenv tox tox-gh-actions pytest pytest-cov mypy coverage[toml]

      - name: "Run tox targets for ${{ matrix.python-version }}"
        run: "python -m tox"
